Add GitHub action to run tests
FreeTubeApp/yt-trending-scraper pull request #10
Opened 2021-11-03 12:23 UTC by ChunkyProgrammer

Tests will run once a day and for each PRs created / merged

2021-11-05 09:47 UTC, efb4f5ff-1298-471a-8973-3d47447115dc submitted a review, later dismissed

2021-11-08 02:21 UTC, PikachuEXE requested changes
Similar to https://github.com/FreeTubeApp/yt-comment-scraper/pull/34#pullrequestreview-799637898

2021-11-10 02:02 UTC, PikachuEXE approved these changes

2021-11-10 06:18 UTC, efb4f5ff-1298-471a-8973-3d47447115dc approved these changes

2022-01-03 22:26 UTC, Hiers approved these changes
Sorry for having been gone for so long.

2022-01-03 22:26 UTC, merged